Repository SUSE/sesdev, pull requests merged in 2019-12, with the labels that each got.

#23 When deploying ses5 with explicit --roles, do not add openattic
  sesdev/__init__.py
Labels: Add To Changelog, bug

#22 If less than 3 storage nodes, increase number of disks
  sesdev/__init__.py
  seslib/__init__.py
Labels: Add To Changelog, bug

#27 Add node info to SSH tunnel command
  sesdev/__init__.py
Labels: enhancement

#31 Display amount of deployed VMs in status output
  seslib/__init__.py
Labels: enhancement

#29 README.md: Added info about roles and services
  README.md
Labels: documentation

#28 Octopus and SES7 deployment with sesboot
  sesdev/__init__.py
  seslib/__init__.py
  seslib/templates/Vagrantfile.j2
  seslib/templates/ceph-bootstrap/ceph_bootstrap_deployment.sh.j2
  seslib/templates/provision.sh.j2
  setup.cfg
Labels: feature

#32 Miscellaneous packaging tweaks
  .github/workflows/linting.yml
  .gitignore
  requirements.txt
  seslib/__init__.py
  setup.cfg
Labels: cleanup
