Repository SUSE/sesdev, pull requests merged in 2019-11, with the labels that each got.

#5 spec: Update and simplify packaging for Fedora and add EL8 support
  sesdev.spec
  sesdev/__init__.py
  setup.py
Labels: packaging

#8 Handle Ctrl+C on deployment creation
  CHANGELOG.md
  sesdev/__init__.py
Labels: enhancement

#11 test: run pylint and pycodestyle linters
  .github/workflows/linting.yml
  .gitignore
  .pylintrc
  README.md
  requirements.txt
  sesdev/__init__.py
  seslib/__init__.py
  seslib/tools.py
  setup.cfg
  setup.py
Labels: testing

#12 sesdev: add version column to `list` subcommand
  sesdev/__init__.py
  seslib/__init__.py
Labels: Add To Changelog, enhancement

#13 seslib/VERSION_OS_REPO_MAPPING: use filesystems:ceph:master:upstream
  seslib/__init__.py
Labels: Add To Changelog

#10 Add Github Action to publish to OBS
  .github/workflows/obs-publish.yml
  CHANGELOG.md
Labels: packaging

#16 seslib: fix 100% cpu usage in non-block stdout reading
  seslib/tools.py
Labels: Add To Changelog, bug

#14 SUMA deployment in "octopus"
  .pylintrc
  sesdev/__init__.py
  seslib/__init__.py
  seslib/exceptions.py
  seslib/templates/Vagrantfile.j2
  seslib/templates/engine/libvirt/vagrant.node.j2
  seslib/templates/engine/libvirt/vagrant.provider.j2
  seslib/templates/suma/suma_deployment.sh.j2
  setup.cfg
Labels: Add To Changelog, feature

#19 Implement --repo-priority / --no-repo-priority
  README.md
  sesdev/__init__.py
  seslib/__init__.py
  seslib/templates/Vagrantfile.j2
Labels: enhancement
