Repository SUSE/sesdev, pull requests merged in 2020-02, with the labels that each got.

#71 Allow user to specify custom private key file for remote libvirt
  README.md
  sesdev/__init__.py
  seslib/__init__.py
  seslib/templates/engine/libvirt/vagrant.provider.j2
Labels: Add To Changelog, feature

#69 Implement "vagrant box list" and "vagrant box remove"
  .travis.yml
  README.md
  sesdev.spec
  sesdev/__init__.py
  seslib/__init__.py
  setup.cfg
Labels: Add To Changelog, feature

#72 Miscellaneous spec file cleanups and bugfixes
  sesdev.spec
Labels: Add To Changelog, bug fix, cleanup, packaging

#76 several fixes for octopus/ses7 deployment
  seslib/templates/ceph-bootstrap/ceph_bootstrap_deployment.sh.j2
  seslib/templates/provision.sh.j2
Labels: bug fix

#78 Pillar is now automatically configured by ceph-bootstrap
  seslib/templates/ceph-bootstrap/ceph_bootstrap_deployment.sh.j2
Labels: Add To Changelog, cleanup

#74 pylintrc: ignore libvirt module
  .pylintrc
  README.md
Labels: cleanup, documentation

#79 [AFTER: M4 RELEASE] Pillar is now automatically configured by ceph-bootstrap
  seslib/templates/ceph-bootstrap/ceph_bootstrap_deployment.sh.j2
  seslib/templates/provision.sh.j2
Labels: Add To Changelog, cleanup

#77 spec: add Fedora-specific Requires
  sesdev.spec
Labels: Add To Changelog, packaging

#83 seslib: fix Ceph repos for ses5, ses6, ses7
  seslib/__init__.py
Labels: Add To Changelog, bug fix

#87 ceph_bootstrap: restart salt-master after ceph-bootstrap installation
  seslib/templates/ceph-bootstrap/ceph_bootstrap_deployment.sh.j2
Labels: bug fix

#94 README.md: make installation instructions less confusing
  README.md
Labels: documentation

#84 Increase chances of getting the latest ses7 packages
  seslib/__init__.py
Labels: Add To Changelog, bug fix

#90 [AFTER: #84] seslib: add SES7 Internal Media when --qa-test given
  seslib/__init__.py
  seslib/exceptions.py
Labels: Add To Changelog, bug fix

#86 ceph_bootstrap_deployment: log cephadm and ceph-bootstrap version
  seslib/templates/ceph-bootstrap/ceph_bootstrap_deployment.sh.j2
Labels: Add To Changelog, feature

#93 libvirt/network: autostart networks per default
  seslib/__init__.py
Labels: Add To Changelog, feature

#81 Remove any orphaned images after destroy
  sesdev/__init__.py
  seslib/__init__.py
Labels: Add To Changelog, bug fix

#88 tools/run_async: decode stderr bytes
  seslib/exceptions.py
  seslib/tools.py
Labels: Add To Changelog, bug fix

#98 README.md: add Table of Contents
  README.md
Labels: documentation

#101 Implement "sesdev scp" feature
  README.md
  sesdev/__init__.py
  seslib/__init__.py
  seslib/exceptions.py
Labels: Add To Changelog, feature

#104 deepsea_deployment.sh: try test.ping in a loop
  seslib/templates/deepsea/deepsea_deployment.sh.j2
Labels: bug fix

#105 added another salt-minion restart after salt-master installation
  seslib/templates/provision.sh.j2
Labels: bug fix

#108 Fix NTP issue that was causing SES5 deployment to fail
  seslib/templates/deepsea/ses5_pre_stage_0.sh.j2
  seslib/templates/provision.sh.j2
Labels: bug fix

#109 HOWTORELEASE.md: tweak the commands so they actually work
  HOWTORELEASE.md
Labels: documentation

#111 seslib: by default, a mgr for every mon
  seslib/__init__.py
Labels: cleanup

#113 provision: remove which RPM from test environment
  seslib/templates/provision.sh.j2
Labels: Add To Changelog, bug fix

#112 Migrate ceph-bootstrap-qa to sesdev (part 2)
  qa/README.rst
  qa/common/common.sh
  qa/common/helper.sh
  qa/common/json.sh
  qa/common/zypper.sh
  qa/health-ok.sh
  sesdev.spec
  sesdev/__init__.py
  seslib/__init__.py
  seslib/templates/Vagrantfile.j2
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
  seslib/templates/provision.sh.j2
Labels: Add To Changelog, feature

#117 ceph_salt_deployment: disable system update and reboot
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog

#116 README.md: add "Common pitfalls" section
  README.md
Labels: documentation

#120 sesdev: give the user a way to specify --no-deploy-*
  sesdev/__init__.py
Labels: Add To Changelog, bug fix

#127 Return with a non-zero exit code in a failure case
  sesdev/__init__.py
Labels: Add To Changelog, bug fix

#125 sesdev: add --non-interactive option to "sesdev create"
  sesdev/__init__.py
  seslib/__init__.py
Labels: Add To Changelog, feature
