Repository SUSE/sesdev, pull requests merged in 2020-08, with the labels that each got.

#421 Miscellaneous code tweaks
  sesdev/__init__.py
  seslib/deployment.py
  seslib/tools.py
Labels: cleanup

#424 setup.cfg: fix "options.package_data" file list
  setup.cfg
Labels: Add To Changelog, bug fix

#432 ceph_salt_deployment: extend OSD deployment timeout
  seslib/deployment.py
  seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog

#434 caasp: set num_disks in same way as for ceph deployments
  README.md
  sesdev/__init__.py
  seslib/constant.py
  seslib/deployment.py
  seslib/templates/caasp/master.sh.j2
Labels: Add To Changelog

#435 vet_configuration: vet caasp4 roles more carefully
  README.md
  seslib/deployment.py
  seslib/exceptions.py
  seslib/templates/caasp/master.sh.j2
Labels: Add To Changelog, cleanup

#438 caasp: update to caasp 4.5
  sesdev/__init__.py
  seslib/constant.py
  seslib/templates/caasp/master.sh.j2
  seslib/templates/caasp/provision.sh.j2
Labels: Add To Changelog

#436 cephadm: allow preparation of cluster for manual deployment
  seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog

#437 deepsea: add ganesha roles to policy.cfg
  seslib/templates/salt/deepsea/nautilus_policy.cfg.j2
  seslib/templates/salt/deepsea/ses5_policy.cfg.j2
Labels: Add To Changelog, bug fix

#439 deployment: disks even when explicit storage role not given
  seslib/deployment.py
Labels: Add To Changelog

#441 cleanup: move code out of Deployment/_generate_nodes()
  seslib/deployment.py
Labels: Add To Changelog, cleanup

#444 cleanup: streamline unit testing and code linting
  .travis.yml
  sesdev/__init__.py
  seslib/box.py
  seslib/constant.py
  seslib/deployment.py
  seslib/exceptions.py
  seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
  setup.cfg
  setup.py
  tests/test_is_a_glob.py
  tests/test_pytest_smoke.py
  tests/test_sesdev_parse_roles.py
  tests/test_vet_dep_id.py
  tox.ini
Labels: Add To Changelog, cleanup, tests

#431 replace-mgr-modules: refrain from introducing Python 2
  seslib/deployment.py
Labels: Add To Changelog, bug fix

#443 ceph-salt: enable user to control which nodes get "admin" role
  contrib/standalone.sh
  qa/common/common.sh
  qa/common/helper.sh
  qa/health-ok.sh
  seslib/constant.py
  seslib/deployment.py
  seslib/exceptions.py
  seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
  tox.ini
Labels: Add To Changelog, wip-smithfarm-testing

#448 If --ssd option is given, make first additional disk non-rotational
  sesdev/__init__.py
  seslib/deployment.py
  seslib/settings.py
  seslib/templates/provision.sh.j2
Labels: Add To Changelog, feature
