Repository SUSE/sesdev, pull requests merged in 2020-04, with the labels that each got.

#213 seslib: check bootstrap role only when it is relevant
  seslib/__init__.py
Labels: Add To Changelog, bug fix

#200 Added the possibility to deploy from the master branch packages
  sesdev/__init__.py
  seslib/__init__.py
Labels: Add To Changelog, feature

#207 seslib: install sesdev-generated keypair under non-default name
  sesdev/__init__.py
  seslib/__init__.py
  seslib/templates/Vagrantfile.j2
  seslib/templates/provision.sh.j2
Labels: Add To Changelog

#214 Jenkinsfile.integration: Retry jenkins slave deletion
  Jenkinsfile.integration
Labels: Add To Changelog, tests

#210 ceph_salt_deployment: make it easier to install ceph-salt from source
  sesdev/__init__.py
  seslib/__init__.py
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog

#205 deepsea_deployment: run Stage 4 only if justified by roles
  seslib/__init__.py
  seslib/templates/deepsea/deepsea_deployment.sh.j2
Labels: Add To Changelog

#218 seslib: ceph_salt_git_branch might be None
  seslib/__init__.py
Labels: bug fix

#217 seslib: make all str-type settings default to the empty string
  seslib/__init__.py
Labels: Add To Changelog, cleanup

#221 ceph_salt_deployment: use --prefix /usr with "pip install"
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
  seslib/templates/deepsea/deepsea_deployment.sh.j2
Labels: Add To Changelog, bug fix

#209 README.md: Needed packages for all major distros
  README.md
Labels: Add To Changelog, documentation

#224 [AFTER https://github.com/ceph/ceph-salt/pull/162] Use quoted string to set bootstrap configs
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog, needs-qa

#229 Failed to setup a SES5 single-node cluster
  seslib/templates/deepsea/deepsea_deployment.sh.j2
Labels: bug fix

#232 seslib: force ses5 prometheus node to master
  seslib/__init__.py
Labels: Add To Changelog, bug fix

#215 seslib: systemically vet roles on create
  README.md
  sesdev/__init__.py
  seslib/__init__.py
  seslib/exceptions.py
Labels: Add To Changelog, cleanup

#230 templates: extend --qa-test to DeepSea-deployed versions and fix issues preventing it from passing
  .gitignore
  contrib/run-standalone.sh
  contrib/standalone.sh
  qa/common/json.sh
  seslib/__init__.py
  seslib/templates/Vagrantfile.j2
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
  seslib/templates/deepsea/deepsea_deployment.sh.j2
  seslib/templates/deepsea/ses5_pre_stage_0.sh.j2
  seslib/templates/provision.sh.j2
  seslib/templates/qa_test.sh
  seslib/templates/sync_clocks.sh.j2
Labels: Add To Changelog, feature

#235 sesdev: make deployment_id argument optional
  README.md
  sesdev/__init__.py
Labels: Add To Changelog, feature, needs-qa, wip-smithfarm-testing

#227 ceph_salt_deployment.sh: do not refresh/sync pillar data
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog

#234 templates: move test.ping try-wait into a separate file
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
  seslib/templates/deepsea/deepsea_deployment.sh.j2
  seslib/templates/deepsea/ses5_pre_stage_0.sh.j2
  seslib/templates/provision.sh.j2
  seslib/templates/wait_for_minions.sh
Labels: Add To Changelog, cleanup

#243 provision.sh: reinstall certain packages from the update repos
  seslib/templates/provision.sh.j2
Labels: Add To Changelog, bug fix, needs-qa, wip-smithfarm-testing

#246 ceph_salt_deployment: do not provision client-only nodes
  sesdev/__init__.py
  seslib/__init__.py
  seslib/exceptions.py
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
  tests/test_sesdev_parse_roles.py
Labels: Add To Changelog, bug fix

#249 README.md: add known pitfall "Failed to connect socket" error
  README.md
Labels: documentation

#247 Implement feature: '--synced-folder' to nfs mount directories
  README.md
  sesdev/__init__.py
  seslib/__init__.py
  seslib/exceptions.py
  seslib/templates/Vagrantfile.j2
Labels: Add To Changelog, feature

#238 Stop, start, and destroy globbing
  sesdev/__init__.py
  tests/test_is_a_glob.py
Labels: Add To Changelog, feature, wip-smithfarm-testing

#258 ses7, octopus, pacific: Deploy MDSs
  README.md
  contrib/standalone.sh
  qa/common/common.sh
  qa/common/helper.sh
  qa/common/json.sh
  qa/common/zypper.sh
  qa/health-ok.sh
  sesdev/__init__.py
  seslib/__init__.py
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
  seslib/templates/deepsea/nautilus_policy.cfg.j2
  seslib/templates/deepsea/ses5_policy.cfg.j2
  seslib/templates/qa_test.sh
Labels: Add To Changelog, feature, wip-smithfarm-testing

#254 Deployment: silently add "master" and "bootstrap" roles
  seslib/__init__.py
Labels: Add To Changelog

#236 Implement feature "sesdev create makecheck"
  README.md
  contrib/standalone.sh
  sesdev/__init__.py
  seslib/__init__.py
  seslib/exceptions.py
  seslib/templates/caasp/provision.sh.j2
  seslib/templates/makecheck/provision.sh.j2
  seslib/templates/provision.sh.j2
Labels: Add To Changelog, feature

#262 qa: fix maybe_wait_for_mdss test
  qa/README.rst
  qa/common/common.sh
  qa/health-ok.sh
  qa/shellcheck.sh
Labels: Add To Changelog, tests

#259 sesdev: implement "sesdev list --format json"
  contrib/standalone.sh
  sesdev.spec
  sesdev/__init__.py
  setup.cfg
Labels: Add To Changelog, feature, packaging

#265 provision.sh: remove Non-OSS repos on openSUSE
  contrib/standalone.sh
  qa/common/common.sh
  qa/health-ok.sh
  seslib/templates/provision.sh.j2
Labels: Add To Changelog, bug fix, needs-review, wip-smithfarm-testing

#268 sesdev: support Click 6.7
  sesdev/__init__.py
  setup.cfg
Labels: Add To Changelog, bug fix

#271 sesdev: tweak PrettyTable-based deployment list
  sesdev/__init__.py
Labels: Add To Changelog, wip-smithfarm-testing

#275 deepsea: "openattic" role needs Stage 4
  seslib/__init__.py
Labels: Add To Changelog, bug fix

#267 Rename --deepsea-cli and --ceph-salt-deploy options to --salt
  README.md
  sesdev/__init__.py
  seslib/__init__.py
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
  seslib/templates/deepsea/deepsea_deployment.sh.j2
Labels: Add To Changelog, wip-smithfarm-testing

#274 seslib: more robust dashboard tunnelling
  contrib/standalone.sh
  sesdev/__init__.py
  seslib/__init__.py
Labels: Add To Changelog, bug fix, wip-smithfarm-testing

#263 README.md: give some context for the "build: passing" icons
  README.md
Labels: documentation

#261 Remove "disable cephadm bootstrap" functionality
  sesdev/__init__.py
  seslib/__init__.py
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog

#279 provision.sh: refactor PROVISIONED_NODES while loop
  contrib/standalone.sh
  sesdev.spec
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
  seslib/templates/deepsea/deepsea_deployment.sh.j2
  seslib/templates/deepsea/ses5_pre_stage_0.sh.j2
  seslib/templates/provision.sh.j2
  seslib/templates/qa_test.sh.j2
  seslib/templates/wait_for_minions.sh
  seslib/templates/wait_for_minions.sh.j2
Labels: Add To Changelog, bug fix, wip-smithfarm-testing

#280 Rename 'ceph-salt deploy' to 'ceph-salt apply'
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog, wip-smithfarm-testing

#286 seslib: fix "Unused argument" linter warning
  seslib/__init__.py
Labels: Add To Changelog, bug fix, wip-smithfarm-testing

#283 provision.sh.j2: Properly prepare CaaSP nodes
  contrib/standalone.sh
  seslib/templates/provision.sh.j2
Labels: Add To Changelog

#284 contrib/standalone.sh: do not fail because of bsc#1170498
  contrib/standalone.sh
Labels: tests, wip-smithfarm-testing

#288 provision.sh: enable autorefresh on all repos
  seslib/templates/caasp/loadbalancer.sh.j2
  seslib/templates/caasp/master.sh.j2
  seslib/templates/caasp/provision.sh.j2
  seslib/templates/caasp/storage.sh.j2
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
  seslib/templates/deepsea/deepsea_deployment.sh.j2
  seslib/templates/deepsea/ses5_pre_stage_0.sh.j2
  seslib/templates/provision.sh.j2
  seslib/templates/suma/suma_deployment.sh.j2
Labels: Add To Changelog, bug fix, cleanup

#285 ceph_salt_deployment: really sync clocks
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
  seslib/templates/sync_clocks.sh.j2
Labels: Add To Changelog, bug fix, wip-smithfarm-testing

#289 ceph_salt_deployment.sh: rip out time sync code
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog, cleanup

#290 Rename '--stop-before-ceph-salt-deploy' to '--stop-before-ceph-salt-apply'
  sesdev/__init__.py
  seslib/__init__.py
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog, wip-smithfarm-testing
