Repository SUSE/sesdev, pull requests merged in 2020-06, with the labels that each got.

#332 qa: tolerate +1 MGRs in number_of_nodes_actual_vs_expected_test
  qa/common/common.sh
Labels: Add To Changelog, tests

#331 Allow user to re-install ceph-salt from source
  README.md
  sesdev/__init__.py
  seslib/__init__.py
Labels: Add To Changelog, feature, wip-smithfarm-testing

#330 seslib: no longer allow explicit "admin" role
  seslib/__init__.py
  seslib/exceptions.py
Labels: Add To Changelog, bug fix

#328 sync_clocks.sh: put chronyc calls in try_wait
  seslib/templates/sync_clocks.sh.j2
Labels: Add To Changelog, bug fix

#24 Implement replace-mgr-modules subcommand
  .pylintrc
  README.md
  sesdev/__init__.py
  seslib/__init__.py
  seslib/exceptions.py
Labels: Add To Changelog, feature, wip-smithfarm-testing

#333 seslib: move boilerplate ssh options into a staticmethod
  seslib/__init__.py
Labels: Add To Changelog, cleanup

#334 Drop the --use-deepsea option for {ses7,octopus,pacific}
  sesdev/__init__.py
  seslib/__init__.py
Labels: Add To Changelog, cleanup

#335 Deployment: vet deployment ID before creation
  contrib/standalone.sh
  sesdev/__init__.py
  seslib/__init__.py
  seslib/exceptions.py
  tests/test_vet_dep_id.py
Labels: Add To Changelog

#337 ses7,octopus,pacific: deploy NFS-Ganesha
  qa/common/common.sh
  qa/common/json.sh
  qa/health-ok.sh
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog, feature

#345 cleanup: nodes_with_role
  qa/common/helper.sh
  qa/health-ok.sh
  seslib/__init__.py
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog, cleanup

#344 qa: implement rgw smoke test
  qa/common/common.sh
  qa/common/rgw.sh
  qa/common/zypper.sh
  qa/health-ok.sh
  seslib/templates/qa_test.sh.j2
Labels: Add To Changelog, feature, tests

#350 Default to ".test" instead of ".com" for the cluster TLD
  CHANGELOG.md
  sesdev/__init__.py
  seslib/__init__.py
Labels: Add To Changelog, bug fix

#203 ceph_salt_deployment: deploy OSDs from YAML (ServiceSpec) file
  seslib/__init__.py
  seslib/exceptions.py
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog

#346 qa/common: make "ceph orch ps" test more resilient
  qa/common/common.sh
Labels: Add To Changelog, bug fix, tests

#347 qa: compare systemctl with expected state on each node
  qa/common/common.sh
  qa/common/helper.sh
  qa/common/rgw.sh
  qa/health-ok.sh
  seslib/__init__.py
  seslib/templates/cluster_json.sh.j2
  seslib/templates/provision.sh.j2
  seslib/templates/qa_test.sh.j2
Labels: Add To Changelog, tests

#355 Fix "replace-mgr-modules" when no containers are running on node
  seslib/__init__.py
Labels: bug fix

#351 Add --devel/--product option and add-repo subcommand
  README.md
  contrib/standalone.sh
  sesdev/__init__.py
  seslib/__init__.py
  seslib/exceptions.py
  seslib/templates/Vagrantfile.j2
  seslib/templates/provision.sh.j2
Labels: Add To Changelog, feature

#352 seslib: no longer support nautilus deployment in Tumbleweed
  seslib/__init__.py
Labels: Add To Changelog, cleanup

#353 qa/rgw: get RGW port from /etc/ceph/ceph.conf
  qa/common/rgw.sh
Labels: Add To Changelog, bug fix, tests

#358 README.md: sesdev can be installed on SLE, too, and bridge-utils is not needed
  Jenkinsfile.integration
  README.md
Labels: documentation, tests

#364 provision.sh: fix regression
  seslib/templates/provision.sh.j2
Labels: bug fix

#365 provision.sh: avoid endless while loop
  seslib/templates/provision.sh.j2
Labels: Add To Changelog, bug fix

#361 provision.sh: set up SSH keys earlier
  seslib/templates/provision.sh.j2
Labels: Add To Changelog, bug fix

#341 Implement --filestore option to deploy OSDs with FileStore
  contrib/standalone.sh
  qa/common/common.sh
  qa/common/helper.sh
  qa/health-ok.sh
  sesdev/__init__.py
  seslib/__init__.py
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
  seslib/templates/deepsea/deepsea_deployment.sh.j2
  seslib/templates/qa_test.sh.j2
Labels: Add To Changelog, feature

#363 ceph_salt_deployment.sh: reduce number of "ceph orch apply" calls
  contrib/standalone.sh
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
  seslib/templates/qa_test.sh.j2
Labels: Add To Changelog, cleanup

#199 provisioning: set fqdn through vagrant and leave /etc/hosts alone
  seslib/templates/engine/libvirt/vagrant.node.j2
  seslib/templates/provision.sh.j2
Labels: Add To Changelog, bug fix

#368 qa: do not wait for non-existent daemons to start
  contrib/standalone.sh
  qa/common/common.sh
  qa/common/json.sh
Labels: Add To Changelog, bug fix

#370 qa/rgw: run curl command in try-wait loop to ping RGW
  qa/common/rgw.sh
  qa/health-ok.sh
Labels: Add To Changelog, bug fix, tests
