Repository SUSE/sesdev, pull requests merged in 2020-05, with the labels that each got.

#296 contrib/nukenetz.sh: virtual network destruction
  contrib/nukenetz.sh
Labels: Add To Changelog

#297 setup.cfg: do not break Tumbleweed RPM install
  README.md
  setup.cfg
Labels: Add To Changelog, bug fix

#298 deepsea_deployment: pre-create Stage 4 pools
  seslib/templates/deepsea/create_all_pools_at_once.sh.j2
  seslib/templates/deepsea/deepsea_deployment.sh.j2
  seslib/templates/provision.sh.j2
Labels: Add To Changelog, bug fix

#302 caasp master provision fix
  seslib/templates/caasp/master.sh.j2
Labels: Add To Changelog, bug fix

#301 Add '--stop-before-ceph-orch-apply' option
  sesdev/__init__.py
  seslib/__init__.py
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog, feature

#307 Option '--deploy-osds' no longer exists
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: bug fix

#303 seslib: drop Containers module from SES7 deployment
  sesdev/__init__.py
  seslib/__init__.py
Labels: Add To Changelog, cleanup

#313 ceph_salt_deployment: do not deploy MDS if no mds roles present
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog, bug fix, wip-smithfarm-testing

#315 ceph_salt_deployment: do not force user to change dashboard pw
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog

#309 seslib: convert public methods into private
  seslib/__init__.py
Labels: Add To Changelog, cleanup

#311 provision.sh: remove curl RPM from the environment
  seslib/templates/provision.sh.j2
Labels: Add To Changelog

#317 makecheck: possibly prophylactically downgrade problem packages
  seslib/templates/makecheck/provision.sh.j2
Labels: Add To Changelog, bug fix

#314 Implement RGW deployment in octopus, ses7
  contrib/nukenetz.sh
  qa/common/common.sh
  qa/common/json.sh
  qa/health-ok.sh
  sesdev/__init__.py
  seslib/__init__.py
  seslib/exceptions.py
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog, feature

#310 caasp4: rename "storage" role to "nfs" and drop it from default 4-node deployment
  README.md
  seslib/__init__.py
  seslib/templates/caasp/master.sh.j2
  seslib/templates/caasp/nfs.sh.j2
  seslib/templates/caasp/provision.sh.j2
Labels: Add To Changelog

#319 Make use of 'cephadm' role
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog

#318 contrib/standalone.sh: --no-stop-on-failure option
  contrib/standalone.sh
Labels: Add To Changelog, tests

#320 caasp: do not install salt
  seslib/__init__.py
  seslib/templates/provision.sh.j2
Labels: Add To Changelog

#323 supportconfig: handle /var/log/scc* and /var/log/nts*
  contrib/standalone.sh
  seslib/__init__.py
  seslib/exceptions.py
Labels: Add To Changelog, bug fix

#324 qa: work around cephadm MGR co-location issue
  qa/common/common.sh
Labels: Add To Changelog, tests

#326 ceph_salt_deployment: fix use_salt=True deployment
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog, bug fix, wip-smithfarm-testing

#325 makecheck: possibly prophylactically downgrade libncurses6
  seslib/templates/makecheck/provision.sh.j2
Labels: Add To Changelog
