Repository SUSE/sesdev, pull requests merged in 2020-01, with the labels that each got.

#42 fix example in help of CLI
  sesdev/__init__.py
Labels: documentation

#39 Add option for predefined libvirt networks
  sesdev/__init__.py
  seslib/__init__.py
  seslib/exceptions.py
  seslib/templates/engine/libvirt/vagrant.node.j2
  seslib/templates/provision.sh.j2
Labels: Add To Changelog, enhancement

#50 vagrant: generate random serial number for each attached disk
  seslib/templates/engine/libvirt/vagrant.node.j2
Labels: Add To Changelog

#52 ceph_bootstrap_deployment: ensure minions are responding
  seslib/templates/ceph-bootstrap/ceph_bootstrap_deployment.sh.j2
Labels: Add To Changelog

#55 sesdev create: fix help text
  sesdev/__init__.py
Labels: documentation

#53 Fix node ip generation
  seslib/__init__.py
Labels: bug

#63 Git ignore PyCharm '.idea' directory
  .gitignore
Labels: cleanup

#46 qa: initial qa integration
  .pylintrc
  sesdev/__init__.py
  seslib/__init__.py
  seslib/templates/ceph-bootstrap/ceph_bootstrap_deployment.sh.j2
  seslib/templates/deepsea/deepsea_deployment.sh.j2
  seslib/templates/provision.sh.j2
  seslib/templates/suma/suma_deployment.sh.j2
Labels: Add To Changelog, feature

#62 ceph_bootstrap: use "ceph-bootstrap deploy" command to run ceph-salt formula
  sesdev/__init__.py
  seslib/__init__.py
  seslib/templates/ceph-bootstrap/ceph_bootstrap_deployment.sh.j2
Labels: Add To Changelog, feature

#64 HOWTORELEASE.md: add new documentation file
  HOWTORELEASE.md
Labels: documentation

#65 Revamp --num-disks handling
  sesdev/__init__.py
Labels: Add To Changelog, bug

#66 doc: globally change 'rjfd' to 'SUSE'
  README.md
  sesdev.spec
  setup.cfg
Labels: documentation

#68 ceph_bootstrap_deployment: "ceph-bootstrap -ldebug deploy"
  README.md
  seslib/templates/ceph-bootstrap/ceph_bootstrap_deployment.sh.j2
Labels: Add To Changelog
