Repository SUSE/sesdev, pull requests merged in 2020-03, with the labels that each got.

#130 seslib: correct downstream container for "sesdev create {ses7,octopus}"
  seslib/__init__.py
  seslib/templates/provision.sh.j2
Labels: Add To Changelog, cleanup

#132 README: add a Common Pitfall: "Storage pool not found"
  README.md
Labels: documentation

#131 qa: assert "ceph versions" matches "ceph --version"
  qa/common/common.sh
  qa/common/helper.sh
  qa/health-ok.sh
Labels: Add To Changelog, tests

#133 provision.sh: remove Python 2 so it doesn't pollute the environment
  seslib/templates/provision.sh.j2
Labels: Add To Changelog, cleanup

#115 Rename --ceph-container-image to --image-path
  sesdev/__init__.py
  seslib/__init__.py
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog

#137 seslib: rename --deploy-bootstrap to --cephadm-bootstrap...
  sesdev/__init__.py
  seslib/__init__.py
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog

#129 Implement "sesdev qa-test" command
  sesdev/__init__.py
  seslib/__init__.py
  seslib/templates/Vagrantfile.j2
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog, feature

#123 provision: install "command-not-found", "supportutils", etc. in test environments
  seslib/templates/provision.sh.j2
Labels: Add To Changelog

#140 spec: disable RH/Fedora Python dependendency generator
  sesdev.spec
Labels: packaging

#139 README: add a Common Pitfall for dangling virtual networks
  README.md
Labels: documentation

#138 ceph_salt_deployment: run "ceph-salt status" after "ceph-salt config ls"
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog

#141 qa: fix path to qa scripts for RPM case
  seslib/__init__.py
Labels: Add To Changelog, packaging

#143 ceph_salt_deployment: honor --no-deploy-osds option
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog, bug fix

#89 Let --debug run "vagrant up/destroy" in debug mode
  sesdev/__init__.py
  seslib/__init__.py
Labels: Add To Changelog, feature

#102 seslib: remove host's virtual networks on destroy
  sesdev/__init__.py
  seslib/__init__.py
Labels: Add To Changelog, feature

#118 Add Jenkinsfile.integration for PR testing
  Jenkinsfile.integration
Labels: Add To Changelog, feature

#150 seslib: stop printing misleading device names
  seslib/__init__.py
Labels: Add To Changelog, cleanup

#148 Add prometheus and alertmanager tunnels.
  sesdev/__init__.py
  seslib/__init__.py
Labels: Add To Changelog, feature

#151 tests: enable unit testing via tox
  CONTRIBUTING.rst
  README.md
  setup.cfg
  tests/test_pytest_smoke.py
  tox.ini
Labels: Add To Changelog, tests

#154 Jenkinsfile: Use configured image
  Jenkinsfile.integration
Labels: Add To Changelog, bug fix, tests

#146 Allow user to override parts of OS_REPOS, VERSION_OS_REPO_MAPPING, and IMAGE_PATHS
  README.md
  seslib/__init__.py
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog, feature

#159 README: add "Install on Debian/Ubuntu" section
  README.md
Labels: documentation

#158 seslib: Set admin roles for octopus
  README.md
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog

#161 Change "admin" role semantics and make roles configurable
  README.md
  sesdev/__init__.py
  seslib/__init__.py
  seslib/exceptions.py
  seslib/templates/Vagrantfile.j2
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
  seslib/templates/deepsea/deepsea_deployment.sh.j2
  seslib/templates/deepsea/nautilus_policy.cfg.j2
  seslib/templates/deepsea/nautilus_pre_stage_0.sh.j2
  seslib/templates/deepsea/ses5_policy.cfg.j2
  seslib/templates/deepsea/ses5_pre_stage_0.sh.j2
  seslib/templates/provision.sh.j2
Labels: Add To Changelog, feature, k8s

#167 Vagrantfile,sesdev.spec: require vagrant > 2.2.2
  sesdev.spec
  seslib/templates/Vagrantfile.j2
Labels: Add To Changelog

#163 config.yaml: enable setting of repo priority in version_os_repo_mapping
  README.md
  seslib/__init__.py
  seslib/templates/provision.sh.j2
Labels: Add To Changelog, feature

#170 Use "filesystems:ceph:octopus:upstream" for default cephadm/container build
  README.md
  seslib/__init__.py
Labels: Add To Changelog

#165 Add a bootstrap.sh script and document how to use it
  README.md
  bootstrap.sh
Labels: Add To Changelog, feature

#166 provision.sh: add SUSE:CA repo on ses5
  seslib/templates/provision.sh.j2
Labels: Add To Changelog, bug fix

#175 Implement feature: "sesdev ssh DEP_ID NODE_ID COMMAND"
  sesdev/__init__.py
  seslib/__init__.py
Labels: Add To Changelog, feature

#173 provision.sh: do not fail ses5 deployment if ntp not installed
  seslib/templates/provision.sh.j2
Labels: Add To Changelog, bug fix

#177 provision.sh: Work around podman/runc issue
  seslib/templates/provision.sh.j2
Labels: Add To Changelog, bug fix

#176 Implement feature: "sesdev supportconfig DEPLOYMENT_ID NODE_ID"
  sesdev/__init__.py
  seslib/__init__.py
  seslib/exceptions.py
Labels: Add To Changelog, feature

#178 ceph_salt_deployment.sh: adapt Drive Group string to new syntax
  README.md
  qa/common/common.sh
  qa/health-ok.sh
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog

#180 qa/health-ok.sh: wait for OSD nodes to show up
  qa/common/common.sh
  qa/health-ok.sh
Labels: Add To Changelog, tests

#182 Jenkins improvements
  Jenkinsfile.integration
Labels: Add To Changelog

#183 Set "osd crush chooseleaf type = 0" via bootstrap ceph.conf in very small clusters
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog

#190 ceph_salt_deployment.sh: Fetch github PRs when installing from src
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog

#195 bootstrap.sh: explicitly use python3
  bootstrap.sh
Labels: Add To Changelog, bug fix

#192 Implement --encrypted-osds feature
  sesdev/__init__.py
  seslib/__init__.py
  seslib/templates/deepsea/deepsea_deployment.sh.j2
Labels: Add To Changelog, feature

#197 ceph_salt_deployment: fetch GitHub PRs when needed
  seslib/__init__.py
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog

#186 ceph_salt_deployment: move OSD deployment to sesdev
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog

#202 sesdev: fail when master role is missing
  sesdev/__init__.py
  seslib/exceptions.py
Labels: Add To Changelog

#187 ceph_salt_deployment: sync clocks after deployment
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog, bug fix

#189 ceph_salt_deployment: use sesdev to deploy MONs and MGRs
  sesdev/__init__.py
  seslib/__init__.py
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog

#201 sesdev: uniform --force/--non-interactive
  sesdev/__init__.py
Labels: Add To Changelog, cleanup

#204 seslib: raise exception if more, or less, than one master/bootstrap role
  README.md
  sesdev/__init__.py
  seslib/__init__.py
  seslib/exceptions.py
Labels: Add To Changelog
