Repository SUSE/sesdev, pull requests merged in 2020-11, with the labels that each got.

#553 Expose Ceph Dashboard on CaaSP SES deployment
  seslib/templates/caasp/master.sh.j2
Labels: Add To Changelog, feature, wip-smithfarm-testing

#523 contrib/standalone.sh: add --fqdn test cases
  contrib/standalone.sh
Labels: Add To Changelog, tests

#543 Implement --no-apparmor option
  sesdev/__init__.py
  seslib/deployment.py
  seslib/settings.py
  seslib/templates/provision.sh.j2
  seslib/templates/zypper.j2
Labels: Add To Changelog, feature

#551 spec: pin sesdev-qa version to sesdev version
  sesdev.spec
Labels: Add To Changelog

#552 constant,zypper: use download.nue.suse.com instead of download.suse.de
  seslib/constant.py
  seslib/templates/zypper.j2
Labels: Add To Changelog

#554 doc/README.md: add common pitfall "Failed to intialize libnetcontrol"
  README.md
Labels: Add To Changelog, documentation, wip-smithfarm-testing

#555 deployment_day_2.sh: create CephFS using documented procedure
  seslib/templates/cephadm/deployment_day_2.sh.j2
Labels: Add To Changelog

#556 tox.ini: add "allowexternals = pylint"
  tox.ini
Labels: cleanup, tests

#557 Implement --rgw-ssl option for deploying RGWs with SSL enabled
  sesdev/__init__.py
  seslib/deployment.py
  seslib/settings.py
  seslib/templates/salt/deepsea/deepsea_deployment.sh.j2
  seslib/templates/salt/deepsea/nautilus_policy.cfg.j2
  seslib/templates/salt/deepsea/nautilus_pre_stage_1.sh.j2
  seslib/templates/salt/deepsea/ses6_pre_stage_1.sh.j2
Labels: Add To Changelog, feature

#558 zypper: add repos when needed
  seslib/constant.py
  seslib/deployment.py
  seslib/settings.py
  seslib/templates/zypper.j2
Labels: Add To Changelog

#561 ses7: use product container image when --product given
  contrib/standalone.sh
  seslib/constant.py
  seslib/deployment.py
  seslib/settings.py
Labels: Add To Changelog, bug fix

#562 doc: add helpful details for installing on SLE-15-SP2
  README.md
Labels: documentation

#565 seslib/constant.py: add SES7 Update repo
  seslib/constant.py
Labels: Add To Changelog, bug fix, wip-smithfarm-testing
