Repository SUSE/sesdev, pull requests merged in 2020-10, with the labels that each got.

#519 create: implement --fqdn option
  sesdev/__init__.py
  seslib/deployment.py
  seslib/settings.py
  seslib/templates/provision.sh.j2
Labels: Add To Changelog, feature

#520 Add makecheck-specific repos only in "sesdev create makecheck"
  seslib/constant.py
  seslib/deployment.py
  seslib/settings.py
  seslib/templates/zypper.j2
Labels: Add To Changelog

#521 Revert "ceph_salt_deployment: add 1-minute grace period"
  seslib/templates/cephadm/deployment_day_2.sh.j2
Labels: Add To Changelog, tests

#522 cephadm/deployment_day_2: specify FQDN when appropriate
  README.md
  seslib/templates/cephadm/deployment_day_2.sh.j2
Labels: Add To Changelog, bug fix, wip-smithfarm-testing

#526 templates/zypper: do not install supportutils-plugin-ses in SES[567]
  seslib/templates/zypper.j2
Labels: Add To Changelog

#530 constant: add missing SLE-15-SP[12] Product repos
  seslib/constant.py
Labels: Add To Changelog, cleanup

#531 Implement "sesdev upgrade" subcommand
  sesdev/__init__.py
  seslib/constant.py
  seslib/deployment.py
  seslib/exceptions.py
  seslib/templates/Vagrantfile.j2
  seslib/templates/zypper.j2
Labels: Add To Changelog, feature

#532 Implement "sesdev reboot DEP_ID NODE" command
  sesdev/__init__.py
  seslib/deployment.py
Labels: Add To Changelog, feature, wip-smithfarm-testing

#538 exceptions: have SesDevException return optional exit code
  sesdev/__init__.py
  seslib/exceptions.py
Labels: Add To Changelog, bug fix

#539 deployment: wait for rebooted node to complete boot sequence
  seslib/deployment.py
  seslib/exceptions.py
Labels: Add To Changelog, bug fix

#540 provision.sh: add helper_scripts Jinja template
  seslib/templates/helper_scripts.j2
  seslib/templates/provision.sh.j2
Labels: Add To Changelog

#535 contrib/upgrade-demo-ses6-to-ses7.sh: add upgrade demo script
  contrib/upgrade-demo-ses6-to-ses7.sh
Labels: Add To Changelog, tests

#545 sesdev: fix --filestore
  sesdev/__init__.py
Labels: Add To Changelog, bug fix

#546 cephadm/deployment_day_2.sh.j2: do not fail on defective --dry-run
  seslib/templates/cephadm/deployment_day_2.sh.j2
Labels: Add To Changelog

#548 setup.cfg: include seslib/templates/cephadm/ directory in packaging
  setup.cfg
Labels: Add To Changelog, bug fix

#547 deepsea/nautilus_pre_stage_0.sh: refrain from patching DeepSea
  seslib/templates/salt/deepsea/nautilus_pre_stage_0.sh.j2
Labels: Add To Changelog, bug fix, wip-smithfarm-testing

#550 sesdev --devel flag: let click deduct type
  sesdev/__init__.py
Labels: bug fix
