Repository SUSE/sesdev, pull requests merged in 2020-07, with the labels that each got.

#372 qa: add IGW to existing tests
  qa/common/common.sh
  qa/health-ok.sh
  seslib/templates/cluster_json.sh.j2
Labels: Add To Changelog, tests

#300 cephadm iSCSI deployment
  seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog, feature

#371 sesdev: sanitize makecheck deployment IDs
  sesdev/__init__.py
Labels: Add To Changelog, bug fix

#277 makecheck: reasonable defaults for Ceph repo/branch
  contrib/standalone.sh
  sesdev/__init__.py
  seslib/__init__.py
Labels: Add To Changelog, feature

#373 qa/systemctl_test: better error message when FSID omitted
  seslib/templates/cluster_json.sh.j2
Labels: Add To Changelog, cleanup

#374 qa: implement superficial test for presence of dashboard branding
  qa/common/common.sh
  qa/health-ok.sh
Labels: Add To Changelog, tests

#375 cleanup: replace "grep | wc --lines" with "grep --count"
  seslib/templates/cluster_json.sh.j2
  seslib/templates/wait_for_minions.sh.j2
Labels: Add To Changelog, cleanup

#376 sesdev: raise exception if --roles combined with --single-node
  sesdev/__init__.py
  seslib/exceptions.py
Labels: Add To Changelog, cleanup, wip-smithfarm-testing

#377 cleanup: reduce bloatedness of seslib/__init__.py
  contrib/standalone.sh
  sesdev/__init__.py
  seslib/__init__.py
  seslib/constant.py
  seslib/log.py
  seslib/settings.py
Labels: Add To Changelog, cleanup

#379 qa/common/rgw: fix curl try-wait
  qa/common/rgw.sh
Labels: Add To Changelog, bug fix, tests

#380 cleanup: zero out seslib/__init__.py
  sesdev/__init__.py
  seslib/__init__.py
  seslib/box.py
  seslib/deployment.py
  seslib/node.py
  tests/test_vet_dep_id.py
Labels: Add To Changelog, cleanup

#381 provision.sh: add all repos before installing packages
  seslib/constant.py
  seslib/templates/provision.sh.j2
Labels: Add To Changelog

#382 sesdev: use Luminous roles for SES5
  seslib/constant.py
Labels: Add To Changelog, bug fix

#383 Refactor seslib/templates/provision.sh
  seslib/templates/deepsea/octopus_policy.cfg.j2
  seslib/templates/deepsea/octopus_pre_stage_0.sh.j2
  seslib/templates/deepsea/octopus_pre_stage_4.sh.j2
  seslib/templates/deepsea/ses6_policy.cfg.j2
  seslib/templates/deepsea/ses6_pre_stage_0.sh.j2
  seslib/templates/deepsea/ses6_pre_stage_4.sh.j2
  seslib/templates/deepsea/ses7_policy.cfg.j2
  seslib/templates/deepsea/ses7_pre_stage_0.sh.j2
  seslib/templates/deepsea/ses7_pre_stage_4.sh.j2
  seslib/templates/provision.sh.j2
  seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
  seslib/templates/salt/cluster_json.j2
  seslib/templates/salt/deepsea/create_all_pools_at_once.sh.j2
  seslib/templates/salt/deepsea/deepsea_deployment.sh.j2
  seslib/templates/salt/deepsea/nautilus_policy.cfg.j2
  seslib/templates/salt/deepsea/nautilus_pre_stage_0.sh.j2
  seslib/templates/salt/deepsea/nautilus_pre_stage_4.sh.j2
  seslib/templates/salt/deepsea/octopus_policy.cfg.j2
  seslib/templates/salt/deepsea/octopus_pre_stage_0.sh.j2
  seslib/templates/salt/deepsea/octopus_pre_stage_4.sh.j2
  seslib/templates/salt/deepsea/ses5_policy.cfg.j2
  seslib/templates/salt/deepsea/ses5_pre_stage_0.sh.j2
  seslib/templates/salt/deepsea/ses6_policy.cfg.j2
  seslib/templates/salt/deepsea/ses6_pre_stage_0.sh.j2
  seslib/templates/salt/deepsea/ses6_pre_stage_4.sh.j2
  seslib/templates/salt/deepsea/ses7_policy.cfg.j2
  seslib/templates/salt/deepsea/ses7_pre_stage_0.sh.j2
  seslib/templates/salt/deepsea/ses7_pre_stage_4.sh.j2
  seslib/templates/salt/provision.sh.j2
  seslib/templates/salt/qa_test.j2
  seslib/templates/salt/suma/suma_deployment.sh.j2
  seslib/templates/salt/wait_for_minions.j2
  seslib/templates/sync_clocks.j2
  seslib/templates/zypper.j2
Labels: Add To Changelog, cleanup

#384 sesdev: implement --dry-run for create commands
  contrib/standalone.sh
  sesdev/__init__.py
  seslib/settings.py
Labels: Add To Changelog, feature

#385 ceph_salt_deployment: use mgr/nfs CLI to deploy NFS Ganesha
  qa/common/common.sh
  qa/common/helper.sh
  qa/health-ok.sh
  seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog, feature

#387 'sesdev replace-mgr-modules' should also replace 'bin/cephadm'
  seslib/deployment.py
Labels: Add To Changelog, wip-smithfarm-testing

#390 qa/nfs: run all nfs smoke tests on ses7 as well as octopus
  qa/common/common.sh
Labels: tests

#392 qa: enable dashboard branding test on {octopus,ses7}
  qa/common/common.sh
  seslib/templates/salt/cluster_json.j2
Labels: Add To Changelog, tests

#393 deployment/status: aggregate global parameters
  seslib/deployment.py
Labels: Add To Changelog, cleanup

#394 ceph_salt_deployment: fix off-by-one error in OSDs wait loop
  seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog, cleanup, wip-smithfarm-testing

#395 sesdev: fix --non-interactive/--force handling
  contrib/standalone.sh
  sesdev/__init__.py
  seslib/settings.py
Labels: Add To Changelog, bug fix

#397 zypper: remove rsync if it's installed in the Vagrant Box
  seslib/templates/zypper.j2
Labels: Add To Changelog, cleanup

#399 Improve the "show" subcommand
  sesdev/__init__.py
  seslib/deployment.py
Labels: Add To Changelog, wip-smithfarm-testing

#400 Change --repo-priority default from "True" to "False"
  README.md
  sesdev/__init__.py
Labels: Add To Changelog

#401 deployment: generate static networks on create only
  seslib/deployment.py
Labels: Add To Changelog, bug fix, wip-smithfarm-testing

#409 ceph_salt_deployment: "ceph -s" when OSDs fail to come up
  seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog

#407 ses5: stop patching srv/salt/ceph/time/ntp/default.sls
  seslib/templates/salt/deepsea/ses5_pre_stage_0.sh.j2
Labels: Add To Changelog

#402 seslib: revamp custom_repo
  README.md
  sesdev/__init__.py
  seslib/constant.py
  seslib/deployment.py
  seslib/exceptions.py
  seslib/node.py
  seslib/settings.py
  seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
  seslib/templates/zypper.j2
  seslib/tools.py
  seslib/zypper.py
Labels: Add To Changelog, cleanup

#403 seslib/deployment: try to destroy the whole cluster at once
  README.md
  seslib/deployment.py
Labels: Add To Changelog, bug fix

#411 provision.sh: persist the journal
  seslib/templates/provision.sh.j2
Labels: Add To Changelog

#405 Improve logging and eliminate code duplication
  seslib/box.py
  seslib/deployment.py
  seslib/tools.py
Labels: Add To Changelog, cleanup

#410 deployment: run supportconfig with 1-hour timeout
  seslib/deployment.py
Labels: Add To Changelog, bug fix

#404 log: print log messages to the screen under certain circumstances
  contrib/standalone.sh
  sesdev/__init__.py
  seslib/constant.py
  seslib/exceptions.py
  seslib/log.py
Labels: Add To Changelog, feature

#408 Change "version_os_repo_mapping" to "version_devel_repos"
  README.md
  contrib/standalone.sh
  seslib/constant.py
  seslib/deployment.py
  seslib/settings.py
Labels: Add To Changelog, cleanup

#413 ceph_salt_deployment.sh: extend OSD timeout
  seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog

#414 sesdev: non-create, non-box functions in alphabetical order
  sesdev/__init__.py
Labels: Add To Changelog, cleanup

#415 ceph_salt_deployment: implement "--stop_before_ceph_orch_apply"
  seslib/templates/makecheck/provision.sh.j2
  seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
  seslib/templates/salt/deepsea/deepsea_deployment.sh.j2
Labels: Add To Changelog, bug fix

#416 Unify role-related constants
  sesdev/__init__.py
  seslib/constant.py
  seslib/deployment.py
  seslib/node.py
  seslib/settings.py
Labels: Add To Changelog, cleanup

#419 settings: rename straggler version_os_repo_mappings
  contrib/standalone.sh
  seslib/settings.py
Labels: Add To Changelog, bug fix
