Repository SUSE/sesdev, pull requests merged in 2020-09, with the labels that each got.

#447 Drop ceph-salt '/system_update' config
  seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog

#449 ceph_salt_deployment: tolerate additional bootstrap MONs/MGRs
  seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog

#452 ceph_salt_deployment: prevent Vagrant from deleting master node
  seslib/templates/caasp/master.sh.j2
  seslib/templates/provision.sh.j2
  seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
  seslib/templates/salt/cluster_json.j2
  seslib/templates/salt/deepsea/create_all_pools_at_once.sh.j2
  seslib/templates/salt/deepsea/deepsea_deployment.sh.j2
  seslib/templates/salt/provision.sh.j2
  seslib/templates/salt/wait_for_minions.j2
  seslib/templates/zypper.j2
Labels: Add To Changelog, bug fix

#456 ceph_salt_deployment: expose ceph-salt errors early
  seslib/templates/provision.sh.j2
  seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog

#457 qa: support opensuse-tumbleweed
  qa/common/common.sh
  qa/common/helper.sh
  qa/common/json.sh
Labels: Add To Changelog, tests

#458 ceph_salt_deployment: explicitly create mds service
  seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog, bug fix

#406 ceph_salt_deployment: do "ceph orch apply --dry-run"
  seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog, wip-smithfarm-testing

#464 qa/common: do not print BADNESS message when test is being skipped
  qa/common/common.sh
Labels: cleanup, tests

#462 deepsea_deployment: really stop before Stage 0
  seslib/templates/salt/deepsea/deepsea_deployment.sh.j2
Labels: Add To Changelog, bug fix

#460 contrib/standalone.sh: adapt to create always returning 0
  contrib/standalone.sh
Labels: Add To Changelog, tests

#463 README.md: explain in more detail how to install Vagrant
  README.md
Labels: documentation

#466 ceph_salt_deployment: always wait for OSDs to appear
  seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog, bug fix

#468 ceph_salt_deployment: deploy MDSs according to documentation
  seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
Labels: Add To Changelog, bug fix

#469 contrib/standalone.sh: remove config.yaml even when failing
  contrib/standalone.sh
Labels: cleanup, tests

#461 Bootstrap minion no longer required to have admin role
  seslib/constant.py
  seslib/deployment.py
Labels: Add To Changelog

#471 Split ceph_salt_deployment.sh into two
  seslib/constant.py
  seslib/deployment.py
  seslib/templates/salt/ceph-salt/deployment_day_1.sh.j2
  seslib/templates/salt/ceph-salt/deployment_day_2.sh.j2
  seslib/templates/salt/deepsea/deepsea_deployment.sh.j2
  seslib/templates/salt/provision.sh.j2
Labels: Add To Changelog, cleanup

#418 ceph_salt: deploy and smoke-test Prometheus
  qa/common/common.sh
  qa/health-ok.sh
  seslib/deployment.py
  seslib/templates/salt/ceph-salt/deployment_day_2.sh.j2
  seslib/templates/salt/cluster_json.j2
  seslib/templates/salt/qa_test.j2
  seslib/templates/sync_clocks.j2
Labels: Add To Changelog, wip-smithfarm-testing

#478 contrib/standalone.sh: wipe empty config.yaml
  contrib/standalone.sh
Labels: Add To Changelog, tests

#475 ceph-salt: deploy and smoke-test Grafana
  qa/common/common.sh
  qa/health-ok.sh
  seslib/deployment.py
  seslib/templates/salt/ceph-salt/deployment_day_2.sh.j2
  seslib/templates/salt/cluster_json.j2
  seslib/templates/salt/qa_test.j2
Labels: Add To Changelog, feature

#476 Support official Vagrant boxes from Vagrant Cloud
  contrib/standalone.sh
  sesdev/__init__.py
  seslib/box.py
  seslib/constant.py
  seslib/deployment.py
  seslib/exceptions.py
  seslib/settings.py
Labels: Add To Changelog, feature

#482 ceph-salt: set some network-related config params explicitly
  seslib/deployment.py
  seslib/templates/salt/ceph-salt/deployment_day_1.sh.j2
Labels: Add To Changelog, bug fix, tests

#480 ceph-salt: deploy and smoke-test alertmanager
  qa/common/common.sh
  qa/health-ok.sh
  seslib/deployment.py
  seslib/templates/salt/ceph-salt/deployment_day_2.sh.j2
  seslib/templates/salt/cluster_json.j2
  seslib/templates/salt/qa_test.j2
Labels: Add To Changelog, feature

#484 zypper: install rbd-nbd on all Leap 15.2/SLE-15-SP2 nodes
  seslib/templates/zypper.j2
Labels: Add To Changelog

#486 Add ability to use Ubuntu "Bionic Beaver" 18.04
  README.md
  sesdev/__init__.py
  seslib/constant.py
  seslib/deployment.py
  seslib/exceptions.py
  seslib/settings.py
  seslib/templates/apt.j2
  seslib/templates/provision.sh.j2
  seslib/templates/salt/ceph-salt/deployment_day_1.sh.j2
  seslib/templates/ubuntu/provision.sh.j2
Labels: Add To Changelog, feature

#488 add label for ses deployment on caasp
  seslib/templates/caasp/master.sh.j2
Labels: Add To Changelog

#489 Update pacific repos
  seslib/constant.py
Labels: Add To Changelog

#492 qa/nfs: do not attempt to mount NFS export on "pacific"
  qa/common/common.sh
  qa/health-ok.sh
  seslib/templates/salt/qa_test.j2
Labels: Add To Changelog, tests

#493 deployment: do not assert if starting an existing deployment
  seslib/deployment.py
Labels: Add To Changelog, bug fix

#56 Add support for IPv6
  README.md
  contrib/standalone.sh
  sesdev/__init__.py
  seslib/deployment.py
  seslib/settings.py
  seslib/templates/salt/ceph-salt/deployment_day_1.sh.j2
  seslib/templates/salt/provision.sh.j2
Labels: Add To Changelog, feature

#481 Add new msgr2 secure options to sesdev
  README.md
  sesdev/__init__.py
  seslib/deployment.py
  seslib/settings.py
  seslib/templates/salt/ceph-salt/deployment_day_1.sh.j2
Labels: Add To Changelog, feature

#495 caasp4: remove anti-affinity for mons for single node
  seslib/templates/caasp/master.sh.j2
Labels: Add To Changelog, k8s

#490 Implement --no-provision option to deploy "bare" VMs
  CHANGELOG.md
  sesdev/__init__.py
  seslib/deployment.py
  seslib/settings.py
  seslib/templates/provision.sh.j2
Labels: Add To Changelog, feature

#496 ceph-salt: deploy and smoke-test node-exporter
  qa/common/common.sh
  qa/health-ok.sh
  seslib/deployment.py
  seslib/templates/salt/ceph-salt/deployment_day_2.sh.j2
  seslib/templates/salt/cluster_json.j2
  seslib/templates/salt/qa_test.j2
Labels: Add To Changelog, feature

#501 deployment: use "vagrant up --provision" to start cluster
  sesdev/__init__.py
  seslib/deployment.py
Labels: Add To Changelog

#498 Implement "sesdev link" for linking two clusters
  .pylintrc
  README.md
  contrib/standalone.sh
  sesdev/__init__.py
  seslib/deployment.py
  seslib/tools.py
Labels: Add To Changelog, feature

#512 deployment: do not populate public_network with "0/24"
  seslib/deployment.py
Labels: Add To Changelog, cleanup

#502 Implement "sesdev status" subcommand
  Jenkinsfile.integration
  README.md
  contrib/standalone.sh
  sesdev/__init__.py
  seslib/deployment.py
  seslib/exceptions.py
Labels: Add To Changelog, feature

#514 qa: wait for grafanas to show up before counting them
  qa/common/common.sh
  qa/health-ok.sh
Labels: Add To Changelog, bug fix, tests

#506 Implement "sesdev show DEP_ID --nodes-with-role=ROLE"
  README.md
  contrib/standalone.sh
  sesdev/__init__.py
  seslib/exceptions.py
Labels: Add To Changelog, feature

#306 contrib/deepsea_drive_replace.sh: new test script
  contrib/deepsea_drive_replace.sh
Labels: Add To Changelog, tests

#515 qa: wait longer for cluster to become healthy
  qa/common/common.sh
  qa/common/helper.sh
Labels: Add To Changelog, tests, wip-smithfarm-testing

#513 cleanup: move cephadm Day 2 provisioner to its own subdirectory
  seslib/templates/cephadm/deployment_day_2.sh.j2
  seslib/templates/provision.sh.j2
  seslib/templates/salt/provision.sh.j2
Labels: Add To Changelog, cleanup

#517 Make "sesdev box list" and "sesdev box remove" accept globs
  sesdev/__init__.py
  sesdev/box.py
  seslib/box.py
  seslib/exceptions.py
  seslib/tools.py
  tests/test_is_a_glob.py
Labels: Add To Changelog, feature
