Repository SUSE/sesdev, pull requests merged in 2021-04, with the labels that each got.

#594 zypper: remove python3-base if it's installed
  seslib/templates/zypper.j2
Labels: Add To Changelog, bug fix, wip-smithfarm-testing

#593 contrib/nukevolz.sh: primitive script to recover wasted disk space
  contrib/nukevolz.sh
Labels: Add To Changelog, feature

#596 templates: disallow global ID reclaim
  seslib/templates/cephadm/deployment_day_2.sh.j2
  seslib/templates/salt/deepsea/deepsea_deployment.sh.j2
Labels: Add To Changelog, bug fix, wip-smithfarm-testing

#592 deployment: Remove redundant codes in node network
  seslib/deployment.py
Labels: Add To Changelog, cleanup

#598 fix pylint issues
  seslib/deployment.py
Labels: Add To Changelog, cleanup
