Repository SUSE/sesdev, pull requests merged in 2021-08, with the labels that each got.

#603 constant: make "vagrant create pacific" use Leap 15.3
  sesdev/__init__.py
  seslib/constant.py
  seslib/templates/makecheck/provision.sh.j2
Labels: Add To Changelog, wip-smithfarm-testing

#604 templates/zypper: install basic packages with --no-recommends
  seslib/templates/zypper.j2
Labels: Add To Changelog, cleanup, wip-smithfarm-testing

#606 Fix --stop-before-cephadm-bootstrap
  seslib/deployment.py
  seslib/settings.py
Labels: bug, Add To Changelog, wip-smithfarm-testing
