Repository SUSE/sesdev, pull requests merged in 2021-11, with the labels that each got.

#612 templates/cephadm/deployment_day_2: fix NFS cluster create command
  seslib/templates/cephadm/deployment_day_2.sh.j2
Labels: bug, Add To Changelog

#613 qa: support pacific on Leap 15.3
  .travis.yml
  contrib/run-standalone.sh
  contrib/standalone.sh
  qa/common/common.sh
  qa/common/helper.sh
  qa/common/json.sh
  seslib/templates/cephadm/deployment_day_2.sh.j2
  seslib/templates/provision.sh.j2
  seslib/templates/salt/cluster_json.j2
Labels: tests, Add To Changelog

#617 pycodestyle: Fix issue with yaml.load (use safe_load)
  seslib/settings.py
  tests/test_parse_config_yaml.py
Labels: Add To Changelog, cleanup
