Repository SUSE/sesdev, pull requests merged in 2021-03, with the labels that each got.

#581 sesdev: replace fancy list comprehension with simpleton code
  sesdev/__init__.py
Labels: Add To Changelog, bug fix

#582 fix tox for Python 3.8
  README.md
  tox.ini
Labels: Add To Changelog, bug fix, wip-smithfarm-testing

#579 cephadm: add 'period update' in radosgw deployment
  seslib/templates/cephadm/deployment_day_2.sh.j2
Labels: Add To Changelog, bug fix, wip-smithfarm-testing

#585 zypper.j2: remove Python 2 even on SLE-12-SP3
  contrib/standalone.sh
  seslib/templates/zypper.j2
Labels: Add To Changelog, bug fix

#584 deployment: saner processing of --deepsea-repo, --deepsea-branch
  sesdev/__init__.py
  seslib/constant.py
  seslib/deployment.py
Labels: Add To Changelog, bug fix

#587 constant.py: drop nfs from octopus default roles
  README.md
  sesdev/__init__.py
  seslib/constant.py
Labels: Add To Changelog, bug fix

#589 nautilus_pre_stage_4.sh.j2: adapt to syntax change
  seslib/constant.py
  seslib/templates/salt/deepsea/nautilus_pre_stage_4.sh.j2
Labels: Add To Changelog

#590 qa/common/json.sh: adapt to change in ceph status json format
  qa/common/json.sh
Labels: Add To Changelog, bug fix
